dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

#login_check_route:
#    pattern:   /auth/login_check