<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getSingleGames($user) {

        $qb = $this->createQueryBuilder('g');
        $games = $qb->select('g')
            ->where('g.form = 0')
            ->andWhere(
                $qb->expr()->orX(
                    $qb->expr()->eq('g.firstPlayer', ':user'),
                    $qb->expr()->eq('g.secondPlayer', ':user')
                )
            )
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();

        return $games;
    }

    public function getUserWonGames($user) {

        $qb = $this->createQueryBuilder('g');
        $games = $qb->select('g')
            ->where('g.winner = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();

        return $games;
    }
}
