<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    /**
     * Find team by members entity
     *
     * @param User[] $teamMembers array of team members entity
     * @return array
     */
    public function findTeamByMembers($teamMembers) {

        $playerCount = count($teamMembers);

        $qb = $this->createQueryBuilder('t');

        $builder = $qb->select('t')
            ->where('t.playerCount = :playerCount');

        foreach ($teamMembers as $member) {

            $teamIDs = array();

            if (!$member->getTeams()->count()) {
                return null;
            }

            foreach ($member->getTeams() as $team) {
                $teamIDs[] = $team->getId();
            }

            $builder->andWhere($qb->expr()->in('t.id', $teamIDs));
        }

        $team = $builder->setMaxResults(1)
            ->setParameter('playerCount', $playerCount)
            ->getQuery()
            ->getOneOrNullResult();

        return $team;
    }

    /**
     * Find team by members entity
     *
     * @param array $teamMemberIDs array of member IDs
     * @return array
     */
    public function findTeamByMemberIDs($teamMemberIDs) {

        if (!$teamMemberIDs) {
            return null;
        }

        $teamMember = array();

        foreach($teamMemberIDs as $memberId) {
            $teamMember[] = $this->getEntityManager()
                ->getRepository('AppBundle:User')
                ->findOneBy(array('id' => $memberId));
        }

        return $this->findTeamByMembers($teamMember);
    }
}
